name: Backup repos
on:
  workflow_dispatch:
    types: [backup-repos]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:  
  backup_repos:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    
    steps:      
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::490752553772:role/backup_gh-assume_role-slc
          role-duration-seconds: 2400
          aws-region: eu-central-1

      - name: Install python libraries
        run: |
          pip install requests
          pip install boto3

      - name: Backup repos and upload to S3
        run: |
          ./backup_repos.py
