name: Backup scheduler
on:
  push:
    branches: [ main ]
  schedule:
    - cron: '*/5 * * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:  
  trigger_backup:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    
    steps:      
      - name: Dispatch backup workflow
        env:
          GH_OPS_PAT: ${{ secrets.PAT_OPS_TRIGGER }}
        run: |
          curl -H "authorization: token $GH_OPS_PAT" 'https://api.github.com/repos/ntampakas/backup-repos/actions/workflows/backup_repos.yml/dispatches' -d '{"ref": "backup_gh"}'
